name: Test

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: test
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo =====================
          ls
          echo =====================
          echo "TEST_SECRET: $TEST_SECRET"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
